USE [master]
GO

/****** Object:  Database [ProgrammersTeste]    Script Date: 23/01/2019 08:17:21 ******/
CREATE DATABASE [ProgrammersTeste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProgrammersTeste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\ProgrammersTeste.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProgrammersTeste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\ProgrammersTeste_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProgrammersTeste] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProgrammersTeste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProgrammersTeste] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProgrammersTeste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProgrammersTeste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProgrammersTeste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProgrammersTeste] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProgrammersTeste] SET  MULTI_USER 
GO

ALTER DATABASE [ProgrammersTeste] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProgrammersTeste] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProgrammersTeste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProgrammersTeste] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProgrammersTeste] SET  READ_WRITE 
GO
